### PR TITLE
Bump 'cookie' version

### LINKED ISSUE #301: Bump cookie dependency please - 0.6.0 causing npm audit to fail
cookie 0.6.0 has a newly listed vulnerability - https://github.com/advisories/GHSA-pxg6-pf52-xh8x.

This causes `npm audit` to fail for current version of @azure/functions package.

Please bump cookie dependency to ^0.7.0.

### PR DESCRIPTION
**Pull request by fseitun**
Fixes #301 
bump cookie version to a non-vulnerable version
ref: https://github.com/advisories/GHSA-pxg6-pf52-xh8x

### CODE REVIEW

**Comment by fseitun** [comment]
@microsoft-github-policy-service agree

**Comment by Sarabadu** [comment]
the is a version 1.0.0 now too https://github.com/jshttp/cookie/releases/tag/v1.0.0

**Comment by lasgor** [comment]
There should really be a vulnerability label, and issues/pull requests with this label should get high priority.

**Comment by fseitun** [comment]
@ejizba sorry to ping you, but maybe you can check this out, thanks!

**Comment by hallvictoria** [comment]
Closing in favor of https://github.com/Azure/azure-functions-nodejs-library/pull/310. Thanks for raising this!

**Pull request closed without merging**
